name: presubmit
on: [pull_request, workflow_call, workflow_dispatch]

jobs:
  test:
    name: cargo test --all-features
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: moonrepo/setup-rust@d8048d4fdff0633123678b093726e6d7c8ad6de5
        with:
          inherit-toolchain: true
      - run: sudo apt-get install zsh fish libpam0g-dev
      - run: SHPOOL_LEAVE_TEST_LOGS=true cargo test --all-features
      - name: Archive Logs
        if: always()
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: test-logs
          path: /tmp/shpool-test*/*.log

  # miri does not handle all the IO we do, disabled for now.
  #
  # miri:
  #   name: cargo +nightly miri test
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
  #     - uses: moonrepo/setup-rust@b8edcc56aab474d90c7cf0bb8beeaf8334c15e9f
  #       with:
  #         components: miri
  #         channel: nightly
  #     - run: sudo apt-get install zsh fish
  #     - run: MIRIFLAGS="-Zmiri-disable-isolation" cargo +nightly miri test

  rustfmt:
    name: cargo +nightly fmt -- --check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: moonrepo/setup-rust@d8048d4fdff0633123678b093726e6d7c8ad6de5
        with:
          components: rustfmt
          channel: nightly
      - run: sudo apt-get install libpam0g-dev
      - run: cargo +nightly fmt -- --check

  cranky:
    name: cargo +nightly cranky --all-targets -- -D warnings
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: moonrepo/setup-rust@d8048d4fdff0633123678b093726e6d7c8ad6de5
        with:
          components: clippy
          bins: cargo-cranky@0.3.0
          channel: nightly
      - run: sudo apt-get install zsh fish libpam0g-dev
      - run: cargo +nightly cranky --all-targets -- -D warnings

  deny:
    name: cargo deny --all-features check licenses
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Install Rust toolchain
        uses: moonrepo/setup-rust@d8048d4fdff0633123678b093726e6d7c8ad6de5
        with:
          inherit-toolchain: true
          bins: cargo-deny
      - run: sudo apt-get install libpam0g-dev
      - run: cargo deny --all-features check licenses
